site_name: My Documentation Portal
site_url: https://sitename.example
nav:
  - Importance of Technical Documentation: index.md
  - Workflow of Technical Writing: process-of-writing-tech-doc.md
  - Static Sites: static-sites.md
  - Code Examples: Code-Examples.md
  - Content Tabs: Content-Tabs.md
  - Install Python for Windows: Sample.md
  - Admonitions Example: Admonitions.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: material/book-search
  features:
    - navigation.footer

  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/shuvam-sarkar-49b6a21b8/

copyright: Copyright &copy; 2024 Shuvam Sarkar
  
  
